# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_deps
<<<<<<< HEAD
   - ./travis-tool.sh install_r ggplot2
=======
>>>>>>> 5106718093bd5fecd5643c6a4872015405c6b51c
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
<<<<<<< HEAD
    on_failure: change
=======
    on_failure: change
>>>>>>> 5106718093bd5fecd5643c6a4872015405c6b51c
