theme_minimalist <-
function (base_size = 12, base_family = "sans") 
{
(theme_grey(base_size = base_size, base_family = base_family) + 
 theme(rect = element_rect(fill ='white', linetype = 0, colour = NA),
  axis.line = element_blank(),
  axis.text = element_text(size = rel(1)),
  text = element_text(family = base_family, face = "plain", colour ='#3C3C3C', size = base_size, hjust = 0.5, vjust = 0.5, angle = 0, lineheight = .7),
 # axis.title.x = element_text(), axis.title.y = element_text(angle = 90),
	axis.title = element_blank(),
  axis.ticks = element_blank(),
  legend.background = element_rect(colour = NA), 
  legend.margin = unit(0.2, "cm"), legend.key = element_rect(colour = NA), 
  legend.key.size = unit(1.2, "lines"), legend.key.height = NULL,
  legend.key.width = NULL, legend.text = element_text(family = base_family, size = base_size * 0.8), 
  legend.text.align = NULL,
  legend.title = element_text(family = base_family, size = base_size * 0.8, face = "bold", hjust = 0),
  legend.title.align = NULL,
  legend.position = "top", 
  legend.direction = NULL, 
  legend.justification = "center",
  legend.box = NULL, 
  panel.background = element_rect(fill = "white"), 
  panel.grid = element_line(colour = NULL),
  panel.grid.major = element_line(colour='#A1A1A1'), 
  panel.grid.minor = element_line(colour = NA), 
  panel.margin = unit(0.25, "lines"),
  strip.text = element_text(size = rel(1.25)), 
  strip.text.x = element_text(),
  strip.text.y = element_text(),
  plot.background = element_rect(fill ='white'),
  plot.title = element_text(size = rel(1.5), hjust=0, face="bold"),
  plot.margin = unit(c(1, 1, 1, 1) * 2, "points"),
  strip.background = element_rect(colour = NULL)))
  }
